apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetimesecret
  namespace: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      run: onetimesecret
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: onetimesecret
    spec:
      containers:      
      - name: onetimesecret
        image: atlantbh/onetimesecret
        imagePullPolicy: Always
        env:
        - name: DOMAIN
          value: ots.abhapp.com
        - name: SSL
          value: "true"
        - name: test
          value: test
        ports:
        - containerPort: 7143
          protocol: TCP
