apiVersion: v1
kind: Service
metadata:
  name: onetimesecret
  namespace: internal
  labels:
    run: onetimesecret
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7143
  selector:
    run: onetimesecret
