apiVersion: v1
kind: Service
metadata:
  name: grok-exporter
  namespace: app-monitoring
  labels:
    sidecar_app: grok-exporter
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    targetPort: 9144
    port: 9144
  selector:
    sidecar_app: grok-exporter