apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: app-monitoring
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort 
  ports:
  - protocol: TCP
    name: web
    nodePort: 31100
    port: 9090
    targetPort: 9090