apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app.fullname" . }}-ui
  labels:
{{ include "test-app.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.ui.type }}
  ports:
    - port: {{ .Values.service.ui.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "test-app.name" . }}-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
