apiVersion: v1
kind: Service
metadata:
  labels:
    run: onetimesecret
  name: onetimesecret
  namespace: internal
spec:
  clusterIP: 100.65.197.5
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7143
  selector:
    run: onetimesecret
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
