apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetimesecret
  namespace: internal
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: onetimesecret
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: onetimesecret
    spec:
      containers:
      - env:
        - name: DOMAIN
          value: ots.abhapp.com
        - name: SSL
          value: "true"
        - name: test
          value: test
        image: atlantbh/onetimesecret
        imagePullPolicy: Always
        name: onetimesecret
        ports:
        - containerPort: 7143
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30